modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory
license="All Rights Reserved"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="iss_magicfromtheeast" #mandatory
version="1.1.1" #mandatory
displayName="ISS: Magic From The East" #mandatory
authors="WarPhan" #optional
credits="Thanks Iron431 and Lab3 for creating the main mod. And for our contributors: Amadhe" #optional
contributors="Thanks for our contributors: Amadhe"
description='''Add new schools, spells and related features which inspired from Eastern culture to ISS.'''
enumExtensions="META-INF/enumextensions.json"

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.iss_magicfromtheeast]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[21.0.0-beta,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.iss_magicfromtheeast]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1, 1.21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iss_magicfromtheeast]]
    modId="irons_spellbooks"
    type="required"
    versionRange="[${irons_spells_version},)"
    ordering="NONE"
    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
